apps/pet/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from ..pet.views import index, pet_view, pet_list, pet_edit, pet_delete, PetList, PetCreate

urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^new$', login_required(PetCreate.as_view()), name="new"),
    url(r'^list$', login_required(PetList.as_view()), name="list"),
    url(r'^edit/(?P<id>\d+)$', login_required(pet_edit), name="edit"),
    url(r'^delete/(?P<id>\d+)', login_required(pet_delete), name="delete" )
]

refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pet/', include('apps.pet.urls', namespace="pet")),
    url(r'^adoption/', include('apps.adoption.urls', namespace="adoption")),
    url(r'^user/', include('apps.userapp.urls', namespace="users")),
    url(r'^accounts/login/', login, {'template_name':'user/login.html'}, name='login'),
    url(r'^accounts/logout/', logout_then_login, name='logout')
]

apps/pet/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from ..adoption.models import Person
# Create your models here.


class Vaccine(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.name)


class Pet(models.Model):
    name = models.CharField(max_length=50)
    sex = models.CharField(max_length=10)
    approximated_age = models.IntegerField()
    rescue_date = models.DateField()
    person = models.ForeignKey(Person, null=True, blank=True, on_delete=models.CASCADE)
    vaccine = models.ManyToManyField(Vaccine, blank=True)

apps/pet/forms.py
from django import forms
from ..pet.models import Pet


class PetForm(forms.ModelForm):

    class Meta:
        model = Pet

        fields = [
            'name',
            'sex',
            'approximated_age',
            'rescue_date',
            'person',
            'vaccine'
        ]

        labels = {
            'name': 'Name',
            'sex': 'Sex',
            'approximated_age': 'Approximated Age',
            'rescue_date': 'Rescue date',
            'person': 'Person',
            'vaccine': 'Vaccine'
        }

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'sex': forms.TextInput(attrs={'class': 'form-control'}),
            'approximated_age': forms.TextInput(attrs={'class': 'form-control'}),
            'rescue_date': forms.TextInput(attrs={'class': 'form-control'}),
            'person': forms.Select(attrs={'class': 'form-control'}),
            'vaccine': forms.CheckboxSelectMultiple()
        }

apps/pet/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from ..pet.forms import PetForm
from ..pet.models import Pet
from django.views.generic import ListView, CreateView


def index(request):

    return render(request, 'pet/index.html')


class PetList(ListView):
    model = Pet
    ordering = ['id']
    template_name = 'pet/pet_list.html'  # si no se pasa el toma esa por defecto XD


def pet_list(request):
    pets = Pet.objects.all().order_by('id')
    context = {'Pets': pets}

    return render(request, 'pet/pet_list.html', context)


class PetCreate(CreateView):
    model = Pet
    form_class = PetForm
    template_name = 'pet/pet_form.html'
    success_url = reverse_lazy('pet:list')


def pet_view(request):
    if request.method == 'POST':
        form = PetForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('pet:index')
    else:
        form = PetForm()

    return render(request, 'pet/pet_form.html', {'form': form})


def pet_edit(request, id):
    pet = Pet.objects.get(id=id)

    if request.method == 'GET':
        form = PetForm(instance=pet)
    else:
        form = PetForm(request.POST, instance=pet)
        if form.is_valid():
            form.save()
        return redirect('pet:list')
    return render(request, 'pet/pet_form.html', {'form': form})


def pet_delete(request, id):
    pet = Pet.objects.get(id=id)
    if request.method == 'POST':
        pet.delete()
        return redirect('pet:list')
    return render(request, 'pet/pet_delete.html', {'pet': pet})

templates/pet/index.html
{% extends 'base/base.html' %}

{% block header%}
    <h4>Este en el headerde mascotas </h4>
{% endblock %}

templates/pet/pet_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form action="" method="post">
    {%   csrf_token %}
    <h3>do you want to remove the pet {{ pet.name }}?</h3>
    <div class="text-center">
        <button class="btn btn-danger">
           <i class="fa fa-trash"></i>
            Delete
        </button>
        <a href="{% url 'pet:list'  %}" class="btn btn-secondary">
            <i class="fa fa-ban"></i>
            Cancelar
        </a>
    </div>
</form>
{% endblock %}

templates/pet/pet_form.html
{% extends 'base/base.html' %}

{% block content %}
<form action="" method="post">
    {%   csrf_token %}
    {{ form.as_p }}
    <div class="text-center">
        <button class="btn btn-primary">
           <i class="far fa-save"></i>
            Guardar
        </button>
    </div>
</form>
{% endblock %}

templates/pet/pet_list.html
{% extends 'base/base.html' %}

{% block content %}

    {% if object_list %}
        <table class="table table-hover table-bordered table-striped">
            <thead>
                <th>#</th>
                <th>Name</th>
                <th>Age</th>
                <th>Sex</th>
                <th>Rescue Date</th>
                <th>Person</th>
                <th colspan="2" style="text-align:center">
                    Actions
                </th>
            </thead>
            <tbody>
            {%  for pet in object_list %}
                <tr>
                    <td>{{ pet.id }}</td>
                    <td>{{ pet.name }}</td>
                    <td>{{ pet.approximated_age }}</td>
                    <td>{{ pet.sex }}</td>
                    <td>{{ pet.rescue_date }}</td>
                    <td>
                        {{ pet.person.name }}
                        {{ pet.person.last_name }}
                    </td>
                    <td width="5%" style="padding:0">
                        <a href="{% url 'pet:edit' pet.id %}" class="btn btn-primary btn-block" data-toggle="tooltip" title="Edit">
                            <i class="fa fa-pencil-alt"></i>
                            Edit
                        </a>
                    </td>
                    <td width="5%" style="padding:0">
                        <a href="{% url 'pet:delete' pet.id %}" class="btn btn-danger btn-block" data-toggle="tooltip" title="Delete">
                            <i class="fa fa-trash"></i>
                            Delete
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-warning">
            No found data
        </div>
    {% endif %}

{% endblock %}