apps/adoption/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from ..adoption.views import index_adoption, RequestList, RequestCreate, RequestUpdate, RequestDelete

urlpatterns = [
    url(r'^index$', login_required(index_adoption), name='index'),
    url(r'^request/list$', login_required(RequestList.as_view()), name='request_list'),
    url(r'^request/new$', login_required(RequestCreate.as_view()), name='request_new'),
    url(r'^request/edit/(?P<pk>\d+)$', login_required(RequestUpdate.as_view()), name='request_edit'),
    url(r'^request/delete/(?P<pk>\d+)$', login_required(RequestDelete.as_view()), name='request_delete')
]

refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pet/', include('apps.pet.urls', namespace="pet")),
    url(r'^adoption/', include('apps.adoption.urls', namespace="adoption")),
    url(r'^user/', include('apps.userapp.urls', namespace="users")),
    url(r'^accounts/login/', login, {'template_name':'user/login.html'}, name='login'),
    url(r'^accounts/logout/', logout_then_login, name='logout')
]

apps/adoption/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# Create your models here.


class Person(models.Model):
    name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=70)
    age = models.IntegerField()
    phone = models.CharField(max_length=12)
    email = models.EmailField()
    home = models.TextField()

    def __str__(self):
        return '{} {}'.format(self.name, self.last_name)


class Request(models.Model):
    person = models.ForeignKey(Person, null=True, blank=True)
    number_pet = models.IntegerField()
    reasons = models.TextField()

apps/adoption/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect

from ..adoption.models import Request, Person
from ..adoption.form import RequestForm, PersonForm


def index_adoption(request):
    return HttpResponse("app")


class RequestList(ListView):
    model = Request
    template_name = 'adoption/request_list.html'


class RequestCreate(CreateView):
    model = Request
    template_name = 'adoption/request_form.html'
    form_class = RequestForm
    second_form_class = PersonForm

    success_url = reverse_lazy('adoption:request_list')

    def get_context_data(self, **kwargs):
        context = super(RequestCreate, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET)
        if 'form2' not in context:
            context['form2'] = self.second_form_class(self.request.GET)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        form2 = self.second_form_class(request.POST)

        if form.is_valid() and form2.is_valid():
            requestO = form.save(commit=False)
            requestO.person = form2.save()
            requestO.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form, form2=form2))


class RequestUpdate(UpdateView):
        model = Request
        second_model = Person
        template_name = 'adoption/request_form.html'
        form_class = RequestForm
        second_form_class = PersonForm

        success_url = reverse_lazy('adoption:request_list')

        def get_context_data(self, **kwargs):
            context = super(RequestUpdate, self).get_context_data(**kwargs)
            pk = self.kwargs.get('pk', 0)
            request_v = self.model.objects.get(id=pk)
            person_v = self.second_model.objects.get(id=request_v.person_id)

            if 'form' not in context:
                context['form'] = self.form_class()
            if 'form2' not in context:
                context['form2'] = self.second_form_class(instance=person_v)
            context['id'] = pk
            return context

class RequestDelete(DeleteView):
    model = Request
    template_name = 'adoption/request_delete.html'
    success_url = reverse_lazy('adoption:request_list')

templates/adoption/request_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form action="" method="post">
    {%   csrf_token %}
    <h3>do you want to remove the request # {{ request.id }} of {{ request.person.name }}?</h3>
    <div class="text-center">
        <button class="btn btn-danger">
           <i class="fa fa-trash"></i>
            Delete
        </button>
        <a href="{% url 'adoption:request_list'  %}" class="btn btn-secondary">
            <i class="fa fa-ban"></i>
            Cancelar
        </a>
    </div>
</form>
{% endblock %}

templates/adoption/request_form.html
{% extends 'base/base.html' %}

{% block content %}
<form action="" method="post" class="form-horizontal">
    {%   csrf_token %}

    <div class="row ">
        <div class="col-6">
            <h4>Person Data</h4>
            <div class="form-group col-10">
                <b>{{ form2.name.label }}</b>
                <div>
                    {{ form2.name }}
                </div>
            </div>
            <div class="form-group col-10">
                <b>{{ form2.last_name.label }}</b>
                <div>
                    {{ form2.last_name }}
                </div>
            </div>
            <div class="form-group col-10">
                <b>{{ form2.age.label }}</b>
                <div>
                    {{ form2.age }}
                </div>
            </div>
            <div class="form-group col-10">
                <b>{{ form2.phone.label }}</b>
                <div>
                    {{ form2.phone }}
                </div>
            </div>
            <div class="form-group col-10">
                <b>{{ form2.email.label }}</b>
                <div>
                    {{ form2.email }}
                </div>
            </div>
            <div class="form-group col-10">
                <b>{{ form2.home.label }}</b>
                <div>
                    {{ form2.home }}
                </div>
            </div>
        </div>
        <div class="col-6">
            <h4>Request Data</h4>
            <div class="form-group col-10">
                <b>{{ form.number_pet.label }}</b>
                <div>
                    {{ form.number_pet }}
                </div>
            </div>
            <div class="form-group col-10">
                <b>{{ form.reasons.label }}</b>
                <div>
                    {{ form.reasons }}
                </div>
            </div>
        </div>
    </div>
    <div class="text-center">
        <button class="btn btn-primary">
           <i class="far fa-save"></i>
            Guardar
        </button>
    </div>
</form>
{% endblock %}

templates/adoption/request_list.html
{% extends 'base/base.html' %}

{% block content %}

    {% if object_list %}
        <table class="table table-hover table-bordered table-striped">
            <thead>
                <th>No. Request</th>
                <th>Person</th>
                <th>No. Pet</th>
                <th>Reasons</th>
                <th colspan="2" style="text-align:center">
                    Actions
                </th>
            </thead>
            <tbody>
                {% for request in object_list %}
                    <tr>
                        <td>{{ request.id }}</td>
                        <td>
                            {{ request.person.name }}
                            {{ request.person.last_name }}
                        </td>
                        <td>{{ request.number_pet }}</td>
                        <td>{{ request.reasons }}</td>
                        <td style="padding:0;width:5%">
                            <a href="{% url 'adoption:request_edit' request.id %}" class="btn btn-primary">
                                <i class="fa fa-edit"></i>
                                Editar
                            </a>
                        </td>
                        <td style="padding:0;width:5%">
                            <a href="{% url 'adoption:request_delete' request.id %}" class="btn btn-danger">
                                <i class="fa fa-times"></i>
                                Eliminar
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-warning">
            No hay solicitudes ingresadas
        </div>
    {% endif %}

{% endblock %}