apps/adoption/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from ..adoption.views import index_adoption, RequestList, RequestCreate, RequestUpdate, RequestDelete

urlpatterns = [
    url(r'^index$', login_required(index_adoption), name='index'),
    url(r'^request/list$', login_required(RequestList.as_view()), name='request_list'),
    url(r'^request/new$', login_required(RequestCreate.as_view()), name='request_new'),
    url(r'^request/edit/(?P<pk>\d+)$', login_required(RequestUpdate.as_view()), name='request_edit'),
    url(r'^request/delete/(?P<pk>\d+)$', login_required(RequestDelete.as_view()), name='request_delete')
]

apps/pet/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from ..pet.views import index, pet_view, pet_list, pet_edit, pet_delete, PetList, PetCreate

urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^new$', login_required(PetCreate.as_view()), name="new"),
    url(r'^list$', login_required(PetList.as_view()), name="list"),
    url(r'^edit/(?P<id>\d+)$', login_required(pet_edit), name="edit"),
    url(r'^delete/(?P<id>\d+)', login_required(pet_delete), name="delete" )
]

apps/userapp/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from ..userapp.views import CreatedUser
urlpatterns = [
    url(r'^create', login_required(CreatedUser.as_view()), name="create")
]

refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pet/', include('apps.pet.urls', namespace="pet")),
    url(r'^adoption/', include('apps.adoption.urls', namespace="adoption")),
    url(r'^user/', include('apps.userapp.urls', namespace="users")),
    url(r'^accounts/login/', login, {'template_name':'user/login.html'}, name='login'),
    url(r'^accounts/logout/', logout_then_login, name='logout')
]

templates/base/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="twitter:creator" content="@Luisfer1097" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
    <link href="https://use.fontawesome.com/releases/v5.0.4/css/all.css" rel="stylesheet">
    {% block head %}
    {% endblock %}
</head>
<body>
    {% block navbar %}
        {% include 'base/navbar.html' %}
    {% endblock %}
    <div class="content">
        {% block header %}
            <h4>Header</h4>
        {% endblock %}

        {% block content %}
            <h4>Content</h4>
        {% endblock %}
    </div>
    {% block footer %}
        <h5>Footer</h5>
    {% endblock %}
    <nav class="navbar fixed-bottom navbar-light bg-light">
        <a class="navbar-brand" href="https://twitter.com/Luisfer1097">
            Luis Fernando
        </a>
    </nav>
    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    {% block scripts %}
    {% endblock %}
</body>
</html>

templates/base/login.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="twitter:creator" content="@Luisfer1097" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
    <link href="https://use.fontawesome.com/releases/v5.0.4/css/all.css" rel="stylesheet">
    {% block head %}
    {% endblock %}
</head>
<body>
    {% block navbar %}
        {% include 'base/navbar.html' %}
    {% endblock %}
    <div class="content">
        {% block header %}
            <h4>Header</h4>
        {% endblock %}

        {% block content %}
            <h4>Content</h4>
        {% endblock %}
    </div>
    {% block footer %}
        <h5>Footer</h5>
    {% endblock %}
    <nav class="navbar fixed-bottom navbar-light bg-light">
        <a class="navbar-brand" href="https://twitter.com/Luisfer1097">
            Luis Fernando
        </a>
    </nav>
    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    {% block scripts %}
    {% endblock %}
</body>
</html>

templates/base/navbar.html
<nav class="navbar navbar-expand-sm fixed-top navbar-dark light bg-primary light">
    <a class="navbar-brand" href="#">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:login' %}" target="_blank">Admin</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Pets
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'pet:list' %}">List</a>
                    <a class="dropdown-item" href="{% url 'pet:new' %}">New</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Request
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'adoption:request_list' %}">List</a>
                    <a class="dropdown-item" href="{% url 'adoption:request_new' %}">New</a>
                </div>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'users:create' %}">
                    Usuarios
                </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'logout' %}">
                    <i class="fa fa-sign-out-alt"></i>
                    Log Out
                </a>
            </li>
        </ul>
    </div>
</nav>